# Generated by Django 4.2.6 on 2023-10-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_server", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(default="", max_length=256),
        ),
    ]
