# Generated by Django 4.2.6 on 2023-10-16 11:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_server", "0002_product_description_alter_product_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client_agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("mail", models.DateTimeField(auto_now=True)),
                ("telephone", models.IntegerField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_number", models.CharField(max_length=256)),
                ("sale_moment", models.DateTimeField(auto_now=True)),
                ("client", models.IntegerField()),
                ("seller", models.IntegerField()),
                (
                    "product_list",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), default=list, size=None
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Seller_agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("mail", models.DateTimeField(auto_now=True)),
                ("telephone", models.IntegerField(default="")),
            ],
        ),
    ]
