# Generated by Django 4.2.6 on 2023-10-16 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sales_server", "0003_client_agent_sale_seller_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="sales_server.seller_agent",
            ),
        ),
        migrations.RemoveField(
            model_name="sale",
            name="product_list",
        ),
        migrations.AlterField(
            model_name="sale",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="sales_server.client_agent",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="product_list",
            field=models.ManyToManyField(to="sales_server.product"),
        ),
    ]
